//
//  Constants.swift
//  First Touch Banking
//
//  Created by Syed Uzair Ahmed on 11/26/17.
//  Copyright © 2017 Syed Uzair Ahmed. All rights reserved.
//

import Foundation


class Constants {
    //--------------------stagging
    public static  let clientSecret = "BggBFqk7SLBItjo28fAWRv67tgtcafNrrYlVlHeo"
//    public static let BASE_URL = "https://mobappuat.hblmfb.com/"
    
//    public static let BASE_URL = "https://mobappuat73@hblmfb.com/"
    
    public static let BASE_URL = "https://mobappuat73.hblmfb.com/"
//////   -----------------------------------------------------end
    
    // ------------------Live---------------------
//    public static let BASE_URL = "https://ab.hblmfb.com/"
//    public static let clientSecret = "lKUcYQSkLEYNLKIZTBjumnbppwDx8hRzCdFar7AF"
//---------------------------------------------end
    
    public static let ACCESS_TOKEN = ""
    
    //Countries List

    static let codeToCountries = [
        "AF":"AFGHANISTAN",
        "AL":"ALBANIA",
        "DZ":"ALGERIA",
        "AS":"AMERICAN SAMOA",
        "AD":"ANDORRA",
        "AO":"ANGOLA",
        "AI":"ANGUILLA",
        "AQ":"ANTARCTICA",
        "AG":"ANTIGUA",
        "AR":"ARGENTINA",           
        "AM":"ARMENIA",
        "AW":"ARUBA",
        "AU":"AUSTRALIA",
        "AT":"AUSTRIA",
        "AZ":"AZERBAIJAN",
        "BS":"BAHAMAS",
        "BH":"BAHRAIN",
        "BD":"BANGLADESH",
        "BB":"BARBADOS",
        "BY":"BELARUS",
        "BE":"BELGIUM",
        "BZ":"BELIZE",
        "BJ":"BENIN",
        "BM":"BERMUDA",
        "BT":"BHUTAN",
        "BO":"BOLIVIA",
        "BA":"BOSNIA AND HERZEGOVINA",
        "BW":"BOTSWANA",
        "BR":"BRAZIL",
        "VG" :"BRITISHVIRGIN ISLANDS",
        "BN":"BRUNEI",
        "BG":"BULGARIA",
        "BF":"BURKINA FASO",
        "BI":"BURUNDI",
        "KH":"CAMBODIA",
        "CM":"CAMEROON",
        "CA":"CANADA",
        "KY":"CAYMAN ISLANDS",
        "CF":"CENTRAL AFRICAN REPUBLIC",
        "TD":"CHAD",
        "CL":"CHILE",
        "CN":"CHINA",
        "CX":"CHRISTMAS ISLAND",
        "CO":"COLOMBIA",
        "KM":"COMOROS",
        "CD":"CONGO",
        "CG":"CONGO",
        "CK":"COOK ISLANDS",
        "CR":"COSTA RICA",
        "HR":"CROATIA",
        "CU":"CUBA",
        "CY":"CYPRUS",
        "CZ":"CZECH REPUBLIC",
        "CV":"Cape Verde Islands",
        "DK":"DENMARK",
        "DJ":"DJIBOUTI",
        "DM":"DOMINICA",
        "DO":"DOMINICAN REPUBLIC",
        "EC":"ECUADOR",
        "EG":"EGYPT",
        "SV":"EL SALVADOR",
        "GQ": "EQUATORIAL GUINEA",
        "ER":"ERITREA",
        "EE":"ESTONIA",
        "ET":"ETHIOPIA",
        "EU":"Europe",
        "FK":"FALKLAND ISLANDS",
        "FO":"FAROE ISLANDS",
        "FJ":"FIJI",
        "FI":"FINLAND",
        "FR":"FRANCE",
        "GF":"FRENCH GUIANA",
        "PF":"FRENCH POLYNESIA",
        "GA":"GABON",
        "GM":"GAMBIA",
        "GE":"GEORGIA",
        "DE":"GERMANY",
        "GH":"GHANA",
        "GI":"GIBRALTAR",
        "GR":"GREECE",
        "GL":"GREENLAND",
        "GD":"GRENADA",
        "GP":"GUADELOUPE",
        "GU":"GUAM",
        "GT":"GUATEMALA",
        "GN":"GUINEA",
        "GW":"GUINEA-BISSAU",
        "GY":"GUYANA",
        "HT":"HAITI",
        "HN":"HONDURAS",
        "HK":"HONG KONG",
        "HU":"HUNGARY",
        "IS":"ICELAND",
        "IN":"INDIA",
        "ID":"INDONESIA",
        "IR":"IRAN",
        "IQ":"IRAQ",
        "IE":"IRELAND",
        "IL":"ISRAEL",
        "IT":"ITALY",
        "JM":"JAMAICA",
        "JP":"JAPAN",
        "JO":"JORDAN",
        "KZ":"KAZAKHSTAN",
        "KE":"KENYA",
        "KI":"KIRIBATI",
        "KP":"KOREA North",
        "KR":"KOREA South",
        "KW":"KUWAIT",
        "KG":"KYRGYZSTAN",
        "LV":"LATVIA",
        "LB":"LEBANON",
        "LS":"LESOTHO",
        "LR":"LIBERIA",
        "LY":"LIBYA",
        "LI":"LIECHTENSTEIN",
        "LT":"LITHUANIA ",
        "LU":"LUXEMBOURG",
        "MO":"MACAO",
        "MK":"MACEDONIA",
        "MG":"MADAGASCAR",
        "MW":"MALAWI",
        "MY":"MALAYSIA",
        "MV":"MALDIVES",
        "MT ":"MALTA",
        "MH":"MARSHALL ISLANDS",
        "MQ":"MARTINIQUE",
        "MR":"MAURITANIA",
        "MU":"MAURITIUS",
        "MX":"MEXICO",
        "FM":"MICRONESIA",
        "MD":"MOLDOVA",
        "MC":"MONACO",
        "MN":"MONGOLIA",
        "MS":"MONTSERRAT",
        "MA":"MOROCCO",
        "MZ":"MOZAMBIQUE",
        "MM":"MYANMAR",
        "NA":"NAMIBIA",
        "NR":"NAURU",
        "NP":"NEPAL",
        "NL":"NETHERLANDS",
        "AN":"NETHERLANDS ANTILLES",
        "NC":"NEW CALEDONIA",
        "NZ":"NEW ZEALAND",
        "NI":"NICARAGUA",
        "NE":"NIGER",
        "NG":"NIGERIA",
        "NU":"NIUE",
        "NF":"NORFOLK ISLAND",
        "NO":"NORWAY",
        "OM":"OMAN",
        "OT":"Others",
        "PK":"PAKISTAN",
        "PW":"PALAU",
        "PS":"PALESTINE",
        "PA":"PANAMA",
        "PG":"PAPUA NEW GUINEA",
        "PY":"PARAGUAY",
        "PE":"PERU",
        "PH":"PHILIPPINES",
        "PL":"POLAND",
        "PT":"PORTUGAL",
        "PR":"PUERTO RICO",
        "QA":"QATAR",
        "RO":"ROMANIA",
        "RU":"RUSSIA",
        "RW":"RWANDA",
        "SH":"SAINT HELENA",
        "LC":"SAINT LUCIA",
        "SM":"SAN MARINO",
        "SA":"SAUDI ARABIA",
        "SN":"SENEGAL",
        "RS":"SERBIA",
        "SL":"SIERRA LEONE",
        "SG":"SINGAPORE",
        "SI":"SLOVENIA",
        "SB":"SOLOMON ISLANDS",
        "SO":"SOMALIA",
        "ZA":"SOUTH AFRICA",
        "ES":"SPAIN",
        "LK":"SRI LANKA",
        "SD":"SUDAN",
        "SR":"SURINAME",
        "SZ":"SWAZILAND",
        "SE":"SWEDEN",
        "CH":"SWITZERLAND",
        "SY":"SYRIA",
        "TW":"TAIWAN",
        "TJ":"TAJIKISTAN",
        "TZ":"TANZANIA",
        "TH":"THAILAND",
        "TG":"TOGO",
        "TK":"TOKELAU",
        "TN":"TUNISIA",
        "TR":"TURKEY",
        "TM":"TURKMENISTAN",
        "TC":"TURKS AND CAICOS ISLANDS",
        "TV":"TUVALU",
        "UG":"UGANDA",
        "UA":"UKRAINE",
        "AE":"UNITED ARAB EMIRATES",
        "GB":"UNITED KINGDOM",
        "US":"UNITED STATES OF AMERICA",
        "UY":"URUGUAY",
        "VI":"US VIRGIN ISLANDS",
        "UZ":"UZBEKISTAN",
        "VU":"VANUATU",
        "VA":"VATICAN CITY",
        "VE":"VENEZUELA",
        "VN":"VIETNAM",
        "WF":"Wallis and Futuna Islands",
        "YE":"YEMEN",
        "YU":"Yugoslavia",
        "ZM":"ZAMBIA",
        "ZW":"ZIMBABWE"
    ];
    
  static  let countriesToCode = [
        
        "AFGHANISTAN":"AF",
        "ALBANIA":"AL",
        "ALGERIA":"DZ",
        "AMERICAN SAMOA":"AS",
        "ANDORRA":"AD",
        "ANGOLA":"AO",
        "ANGUILLA":"AI",
        "ANTARCTICA":"AQ",
        "ANTIGUA":"AG",
        "ARGENTINA":"AR",
        "ARMENIA":"AM",
        "ARUBA":"AW",
        "AUSTRALIA":"AU",
        "AUSTRIA":"AT",
        "AZERBAIJAN":"AZ",
        "BAHAMAS":"BS",
        "BAHRAIN":"BH",
        "BANGLADESH":"BD",
        "BARBADOS":"BB",
        "BELARUS":"BY",
        "BELGIUM":"BE",
        "BELIZE":"BZ",
        "BENIN":"BJ",
        "BERMUDA":"BM",
        "BHUTAN":"BT",
        "BOLIVIA":"BO",
        "BOSNIA AND HERZEGOVINA":"BA",
        "BOTSWANA":"BW",
        "BRAZIL":"BR",
        "BRITISHVIRGIN ISLANDS":"VG",
        "BRUNEI":"BN",
        "BULGARIA":"BG",
        "BURKINA FASO":"BF",
        "BURUNDI":"BI",
        "CAMBODIA":"KH",
        "CAMEROON":"CM",
        "CANADA":"CA",
        "CAYMAN ISLANDS":"KY",
        "CENTRAL AFRICAN REPUBLIC":"CF",
        "CHAD":"TD",
        "CHILE":"CL",
        "CHINA":"CN",
        "CHRISTMAS ISLAND":"CX",
        "COLOMBIA":"CO",
        "COMOROS":"KM",
        "CONGO":"CD",
        "CONGO":"CG",
        "COOK ISLANDS":"CK",
        "COSTA RICA":"CR",
        "CROATIA":"HR",
        "CUBA":"CU",
        "CYPRUS":"CY",
        "CZECH REPUBLIC":"CZ",
        "Cape Verde Islands":"CV",
        "DENMARK":"DK",
        "DJIBOUTI":"DJ",
        "DOMINICA":"DM",
        "DOMINICAN REPUBLIC":"DO",
        "ECUADOR":"EC",
        "EGYPT":"EG",
        "EL SALVADOR":"SV",
        "EQUATORIAL GUINEA":"GQ",
        "ERITREA":"ER",
        "ESTONIA":"EE",
        "ETHIOPIA":"ET",
        "Europe":"EU",
        "FALKLAND ISLANDS":"FK",
        "FAROE ISLANDS":"FO",
        "FIJI":"FJ",
        "FINLAND":"FI",
        "FRANCE":"FR",
        "FRENCH GUIANA":"GF",
        "FRENCH POLYNESIA":"PF",
        "GABON":"GA",
        "GAMBIA":"GM",
        "GEORGIA":"GE",
        "GERMANY":"DE",
        "GHANA":"GH",
        "GIBRALTAR":"GI",
        "GREECE":"GR",
        "GREENLAND":"GL",
        "GRENADA":"GD",
        "GUADELOUPE":"GP",
        "GUAM":"GU",
        "GUATEMALA":"GT",
        "GUINEA":"GN",
        "GUINEA-BISSAU":"GW",
        "GUYANA":"GY",
        "HAITI":"HT",
        "HONDURAS":"HN",
        "HONG KONG":"HK",
        "HUNGARY":"HU",
        "ICELAND":"IS",
        "INDIA":"IN",
        "INDONESIA":"ID",
        "IRAN":"IR",
        "IRAQ":"IQ",
        "IRELAND":"IE",
        "ISRAEL":"IL",
        "ITALY":"IT",
        "JAMAICA":"JM",
        "JAPAN":"JP",
        "JORDAN":"JO",
        "KAZAKHSTAN":"KZ",
        "KENYA":"KE",
        "KIRIBATI":"KI",
        "KOREA North":"KP",
        "KOREA South":"KR",
        "KUWAIT":"KW",
        "KYRGYZSTAN":"KG",
        "LATVIA":"LV",
        "LEBANON":"LB",
        "LESOTHO":"LS",
        "LIBERIA":"LR",
        "LIBYA":"LY",
        "LIECHTENSTEIN":"LI",
        "LITHUANIA ":"LT",
        "LUXEMBOURG":"LU",
        "MACAO":"MO",
        "MACEDONIA":"MK",
        "MADAGASCAR":"MG",
        "MALAWI":"MW",
        "MALAYSIA":"MY",
        "MALDIVES":"MV",
        "MALTA":"MT",
        "MARSHALL ISLANDS":"MH",
        "MARTINIQUE":"MQ",
        "MAURITANIA":"MR",
        "MAURITIUS":"MU",
        "MEXICO":"MX",
        "MICRONESIA":"FM",
        "MOLDOVA":"MD",
        "MONACO":"MC",
        "MONGOLIA":"MN",
        "MONTSERRAT":"MS",
        "MOROCCO":"MA",
        "MOZAMBIQUE":"MZ",
        "MYANMAR":"MM",
        "NAMIBIA":"NA",
        "NAURU":"NR",
        "NEPAL":"NP",
        "NETHERLANDS":"NL",
        "NETHERLANDS ANTILLES":"AN",
        "NEW CALEDONIA":"NC",
        "NEW ZEALAND":"NZ",
        "NICARAGUA":"NI",
        "NIGER":"NE",
        "NIGERIA":"NG",
        "NIUE":"NU",
        "NORFOLK ISLAND":"NF",
        "NORWAY":"NO",
        "OMAN":"OM",
        "Others":"OT",
        "PAKISTAN":"PK",
        "PALAU":"PW",
        "PALESTINE":"PS",
        "PANAMA":"PA",
        "PAPUA NEW GUINEA":"PG",
        "PARAGUAY":"PY",
        "PERU":"PE",
        "PHILIPPINES":"PH",
        "POLAND":"PL",
        "PORTUGAL":"PT",
        "PUERTO RICO":"PR",
        "QATAR":"QA",
        "ROMANIA":"RO",
        "RUSSIA":"RU",
        "RWANDA":"RW",
        "SAINT HELENA":"SH",
        "SAINT LUCIA":"LC",
        "SAN MARINO":"SM",
        "SAUDI ARABIA":"SA",
        "SENEGAL":"SN",
        "SERBIA":"RS",
        "SIERRA LEONE":"SL",
        "SINGAPORE":"SG",
        "SLOVENIA":"SI",
        "SOLOMON ISLANDS":"SB",
        "SOMALIA":"SO",
        "SOUTH AFRICA":"ZA",
        "SPAIN":"ES",
        "SRI LANKA":"LK",
        "SUDAN":"SD",
        "SURINAME":"SR",
        "SWAZILAND":"SZ",
        "SWEDEN":"SE",
        "SWITZERLAND":"CH",
        "SYRIA":"SY",
        "TAIWAN":"TW",
        "TAJIKISTAN":"TJ",
        "TANZANIA":"TZ",
        "THAILAND":"TH",
        "TOGO":"TG",
        "TOKELAU":"TK",
        "TUNISIA":"TN",
        "TURKEY":"TR",
        "TURKMENISTAN":"TM",
        "TURKS AND CAICOS ISLANDS":"TC",
        "TUVALU":"TV",
        "UGANDA":"UG",
        "UKRAINE":"UA",
        "UNITED ARAB EMIRATES":"AE",
        "UNITED KINGDOM":"GB",
        "UNITED STATES OF AMERICA":"US",
        "URUGUAY":"UY",
        "US VIRGIN ISLANDS":"VI",
        "UZBEKISTAN":"UZ",
        "VANUATU":"VU",
        "VATICAN CITY":"VA",
        "VENEZUELA":"VE",
        "VIETNAM":"VN",
        "Wallis and Futuna Islands":"WF",
        "YEMEN":"YE",
        "Yugoslavia":"YU",
        "ZAMBIA":"ZM",
        "ZIMBABWE":"ZW"
        
    ];
}
class GlobalOTPTypes {
    
    public static let OTP_CASH_OUT = "B"                                                 //CASH OUT
    public static let OTP_IBFT = "IBFT"                                                  //IBFT
    public static let OTP_FUNDS_TRANSFER = "FT"                                          //FUNDS TRANSFER
    public static let OTP_BILL_PAYMENT = "BP"                                            //BILL PAYMENT
    public static let OTP_MOBILE_TOPUP = "TOP"                                           //MOBILE TOP UP
    public static let OTP_CONCENT = "TOP"                                                //CONCENT
    public static let OTP_BENEFICARY = "BEN"                                             //BENEFICARY
    public static let OTP_LINK_ACCOUNT = "LA"                                            //LINK ACCOUNT
    public static let OTP_BALANCE_PULL = "PUSH"                                          //BENEFICARY
    public static let OTP_BALANCE_PUSH  = "PULL"                                         //BENEFICARY
    
    // LOAD BALANCE
    
    public static let LOAD_BALANCE_PUSH  = "PUSH"
    public static let LOAD_BALANCE_PULL  = "PULL"
    public static let REQUIRED_OTP_YES  = "Y"
    public static let REQUIRED_OTP_NO  = "N"
   
}
